name: app_voluntario
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_map: ^8.1.1
  flutter_secure_storage: ^9.0.0
  geocoding: ^2.1.1
  http: ^1.4.0
  latlong2: ^0.9.1
  table_calendar: ^3.2.0
  url_launcher: ^6.3.1
  lottie: ^3.1.0
  share_plus: ^7.2.1
  percent_indicator: ^4.2.3
  image_picker: ^1.0.7
  permission_handler: ^11.3.1
  flutter_multi_formatter: ^2.4.0
  mask_text_input_formatter: ^2.4.0
  fluttertoast: ^8.2.1
  provider: ^6.1.1
  flutter_svg: ^2.0.7
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0 
  fl_chart: ^0.66.0


dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icone_app.png" 
  min_sdk_android: 21
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/animations/congrats.json
    - assets/animations/confetti.json
    - assets/animations/trophy.json
    - assets/animations/avatar1.json
    - assets/animations/avatar2.json
    - assets/animations/loading.json
    - assets/icon/icone_app.png
    - assets/icon/icone_app2.svg
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
